# Copyright 2025 the LlamaFactory team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MODELS = {
    'Qwen 系列': [
        ('Qwen/Qwen2-0.5B', 'Qwen2-0.5B'),
        ('Qwen/Qwen2-1.5B', 'Qwen2-1.5B'),
        ('Qwen/Qwen2-7B', 'Qwen2-7B'),
        ('Qwen/Qwen2-72B', 'Qwen2-72B'),
        ('Qwen/Qwen2-57B-A14B', 'Qwen2-MoE-57B-A14B'),
        ('Qwen/Qwen2-0.5B-Instruct', 'Qwen2-0.5B-Instruct'),
        ('Qwen/Qwen2-1.5B-Instruct', 'Qwen2-1.5B-Instruct'),
        ('Qwen/Qwen2-7B-Instruct', 'Qwen2-7B-Instruct'),
        ('Qwen/Qwen2-72B-Instruct', 'Qwen2-72B-Instruct'),
        ('Qwen/Qwen2-57B-A14B-Instruct', 'Qwen2-MoE-57B-A14B-Instruct'),
        ('Qwen/Qwen2-0.5B-Instruct-GPTQ-Int8', 'Qwen2-0.5B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2-0.5B-Instruct-GPTQ-Int4', 'Qwen2-0.5B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-0.5B-Instruct-AWQ', 'Qwen2-0.5B-Instruct-AWQ'),
        ('Qwen/Qwen2-1.5B-Instruct-GPTQ-Int8', 'Qwen2-1.5B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2-1.5B-Instruct-GPTQ-Int4', 'Qwen2-1.5B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-1.5B-Instruct-AWQ', 'Qwen2-1.5B-Instruct-AWQ'),
        ('Qwen/Qwen2-7B-Instruct-GPTQ-Int8', 'Qwen2-7B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2-7B-Instruct-GPTQ-Int4', 'Qwen2-7B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-7B-Instruct-AWQ', 'Qwen2-7B-Instruct-AWQ'),
        ('Qwen/Qwen2-72B-Instruct-GPTQ-Int8', 'Qwen2-72B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2-72B-Instruct-GPTQ-Int4', 'Qwen2-72B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-72B-Instruct-AWQ', 'Qwen2-72B-Instruct-AWQ'),
        ('Qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4', 'Qwen2-57B-A14B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-Math-1.5B', 'Qwen2-Math-1.5B'),
        ('Qwen/Qwen2-Math-7B', 'Qwen2-Math-7B'),
        ('Qwen/Qwen2-Math-72B', 'Qwen2-Math-72B'),
        ('Qwen/Qwen2-Math-1.5B-Instruct', 'Qwen2-Math-1.5B-Instruct'),
        ('Qwen/Qwen2-Math-7B-Instruct', 'Qwen2-Math-7B-Instruct'),
        ('Qwen/Qwen2-Math-72B-Instruct', 'Qwen2-Math-72B-Instruct'),
        ('Qwen/Qwen2-Audio-7B', 'Qwen2-Audio-7B'),
        ('Qwen/Qwen2-Audio-7B-Instruct', 'Qwen2-Audio-7B-Instruct'),
        ('Qwen/Qwen2-VL-2B', 'Qwen2-VL-2B'),
        ('Qwen/Qwen2-VL-7B', 'Qwen2-VL-7B'),
        ('Qwen/Qwen2-VL-72B', 'Qwen2-VL-72B'),
        ('Qwen/Qwen2-VL-2B-Instruct', 'Qwen2-VL-2B-Instruct'),
        ('Qwen/Qwen2-VL-7B-Instruct', 'Qwen2-VL-7B-Instruct'),
        ('Qwen/Qwen2-VL-72B-Instruct', 'Qwen2-VL-72B-Instruct'),
        ('Qwen/Qwen2-VL-2B-Instruct-GPTQ-Int8', 'Qwen2-VL-2B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2-VL-2B-Instruct-GPTQ-Int4', 'Qwen2-VL-2B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-VL-2B-Instruct-AWQ', 'Qwen2-VL-2B-Instruct-AWQ'),
        ('Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int8', 'Qwen2-VL-7B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4', 'Qwen2-VL-7B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-VL-7B-Instruct-AWQ', 'Qwen2-VL-7B-Instruct-AWQ'),
        ('Qwen/Qwen2-VL-72B-Instruct-GPTQ-Int8', 'Qwen2-VL-72B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2-VL-72B-Instruct-GPTQ-Int4', 'Qwen2-VL-72B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2-VL-72B-Instruct-AWQ', 'Qwen2-VL-72B-Instruct-AWQ'),
        ('Qwen/QVQ-72B-Preview', 'QVQ-72B-Preview'),
        ('Qwen/Qwen2.5-0.5B', 'Qwen2.5-0.5B'),
        ('Qwen/Qwen2.5-1.5B', 'Qwen2.5-1.5B'),
        ('Qwen/Qwen2.5-3B', 'Qwen2.5-3B'),
        ('Qwen/Qwen2.5-7B', 'Qwen2.5-7B'),
        ('Qwen/Qwen2.5-14B', 'Qwen2.5-14B'),
        ('Qwen/Qwen2.5-32B', 'Qwen2.5-32B'),
        ('Qwen/Qwen2.5-72B', 'Qwen2.5-72B'),
        ('Qwen/Qwen2.5-0.5B-Instruct', 'Qwen2.5-0.5B-Instruct'),
        ('Qwen/Qwen2.5-1.5B-Instruct', 'Qwen2.5-1.5B-Instruct'),
        ('Qwen/Qwen2.5-3B-Instruct', 'Qwen2.5-3B-Instruct'),
        ('Qwen/Qwen2.5-7B-Instruct', 'Qwen2.5-7B-Instruct'),
        ('Qwen/Qwen2.5-14B-Instruct', 'Qwen2.5-14B-Instruct'),
        ('Qwen/Qwen2.5-32B-Instruct', 'Qwen2.5-32B-Instruct'),
        ('Qwen/Qwen2.5-72B-Instruct', 'Qwen2.5-72B-Instruct'),
        ('Qwen/Qwen2.5-7B-Instruct-1M', 'Qwen2.5-7B-Instruct-1M'),
        ('Qwen/Qwen2.5-14B-Instruct-1M', 'Qwen2.5-14B-Instruct-1M'),
        ('Qwen/Qwen2.5-0.5B-Instruct-GPTQ-Int8', 'Qwen2.5-0.5B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2.5-0.5B-Instruct-GPTQ-Int4', 'Qwen2.5-0.5B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2.5-0.5B-Instruct-AWQ', 'Qwen2.5-0.5B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-1.5B-Instruct-GPTQ-Int8', 'Qwen2.5-1.5B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2.5-1.5B-Instruct-GPTQ-Int4', 'Qwen2.5-1.5B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2.5-1.5B-Instruct-AWQ', 'Qwen2.5-1.5B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-3B-Instruct-GPTQ-Int8', 'Qwen2.5-3B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2.5-3B-Instruct-GPTQ-Int4', 'Qwen2.5-3B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2.5-3B-Instruct-AWQ', 'Qwen2.5-3B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-7B-Instruct-GPTQ-Int8', 'Qwen2.5-7B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2.5-7B-Instruct-GPTQ-Int4', 'Qwen2.5-7B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2.5-7B-Instruct-AWQ', 'Qwen2.5-7B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-14B-Instruct-GPTQ-Int8', 'Qwen2.5-14B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2.5-14B-Instruct-GPTQ-Int4', 'Qwen2.5-14B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2.5-14B-Instruct-AWQ', 'Qwen2.5-14B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-32B-Instruct-GPTQ-Int8', 'Qwen2.5-32B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2.5-32B-Instruct-GPTQ-Int4', 'Qwen2.5-32B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2.5-32B-Instruct-AWQ', 'Qwen2.5-32B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-72B-Instruct-GPTQ-Int8', 'Qwen2.5-72B-Instruct-GPTQ-Int8'),
        ('Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4', 'Qwen2.5-72B-Instruct-GPTQ-Int4'),
        ('Qwen/Qwen2.5-72B-Instruct-AWQ', 'Qwen2.5-72B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-Coder-0.5B', 'Qwen2.5-Coder-0.5B'),
        ('Qwen/Qwen2.5-Coder-1.5B', 'Qwen2.5-Coder-1.5B'),
        ('Qwen/Qwen2.5-Coder-3B', 'Qwen2.5-Coder-3B'),
        ('Qwen/Qwen2.5-Coder-7B', 'Qwen2.5-Coder-7B'),
        ('Qwen/Qwen2.5-Coder-14B', 'Qwen2.5-Coder-14B'),
        ('Qwen/Qwen2.5-Coder-32B', 'Qwen2.5-Coder-32B'),
        ('Qwen/Qwen2.5-Coder-0.5B-Instruct', 'Qwen2.5-Coder-0.5B-Instruct'),
        ('Qwen/Qwen2.5-Coder-1.5B-Instruct', 'Qwen2.5-Math-1.5B-Instruct'),
        ('Qwen/Qwen2.5-Coder-3B-Instruct', 'Qwen2.5-Coder-3B-Instruct'),
        ('Qwen/Qwen2.5-Coder-7B-Instruct', 'Qwen2.5-Math-7B-Instruct'),
        ('Qwen/Qwen2.5-Coder-14B-Instruct', 'Qwen2.5-Coder-14B-Instruct'),
        ('Qwen/Qwen2.5-Coder-32B-Instruct', 'Qwen2.5-Coder-32B-Instruct'),
        ('Qwen/Qwen2.5-Coder-72B-Instruct', 'Qwen2.5-Math-72B-Instruct'),
        ('Qwen/Qwen2.5-Math-1.5B', 'Qwen2.5-Math-1.5B'),
        ('Qwen/Qwen2.5-Math-7B', 'Qwen2.5-Math-7B'),
        ('Qwen/Qwen2.5-Math-72B', 'Qwen2.5-Math-72B'),
        ('Qwen/Qwen2.5-Omni-3B', 'Qwen2.5-Omni-3B'),
        ('Qwen/Qwen2.5-Omni-7B', 'Qwen2.5-Omni-7B'),
        ('Qwen/Qwen2.5-Omni-7B-GPTQ-Int4', 'Qwen2.5-Omni-7B-GPTQ-Int4'),
        ('Qwen/Qwen2.5-Omni-7B-AWQ', 'Qwen2.5-Omni-7B-AWQ'),
        ('Qwen/Qwen2.5-VL-3B-Instruct', 'Qwen2.5-VL-3B-Instruct'),
        ('Qwen/Qwen2.5-VL-7B-Instruct', 'Qwen2.5-VL-7B-Instruct'),
        ('Qwen/Qwen2.5-VL-32B-Instruct', 'Qwen2.5-VL-32B-Instruct'),
        ('Qwen/Qwen2.5-VL-72B-Instruct', 'Qwen2.5-VL-72B-Instruct'),
        ('Qwen/Qwen2.5-VL-3B-Instruct-AWQ', 'Qwen2.5-VL-3B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-VL-7B-Instruct-AWQ', 'Qwen2.5-VL-7B-Instruct-AWQ'),
        ('Qwen/Qwen2.5-VL-72B-Instruct-AWQ', 'Qwen2.5-VL-72B-Instruct-AWQ'),
        ('Qwen/QwQ-32B-Preview', 'QwQ-32B-Preview-Instruct'),
        ('Qwen/QwQ-32B', 'QwQ-32B-Instruct'),
        ('Qwen/Qwen3-0.6B-Base', 'Qwen3-0.6B-Base'),
        ('Qwen/Qwen3-1.7B-Base', 'Qwen3-1.7B-Base'),
        ('Qwen/Qwen3-4B-Base', 'Qwen3-4B-Base'),
        ('Qwen/Qwen3-8B-Base', 'Qwen3-8B-Base'),
        ('Qwen/Qwen3-14B-Base', 'Qwen3-14B-Base'),
        ('Qwen/Qwen3-30B-A3B-Base', 'Qwen3-30B-A3B-Base'),
        ('Qwen/Qwen3-0.6B', 'Qwen3-0.6B-Thinking'),
        ('Qwen/Qwen3-1.7B', 'Qwen3-1.7B-Thinking'),
        ('Qwen/Qwen3-4B', 'Qwen3-4B-Thinking'),
        ('Qwen/Qwen3-4B-Thinking-2507', 'Qwen3-4B-Thinking-2507'),
        ('Qwen/Qwen3-8B', 'Qwen3-8B-Thinking'),
        ('Qwen/Qwen3-14B', 'Qwen3-14B-Thinking'),
        ('Qwen/Qwen3-32B', 'Qwen3-32B-Thinking'),
        ('Qwen/Qwen3-30B-A3B', 'Qwen3-30B-A3B-Thinking'),
        ('Qwen/Qwen3-30B-A3B-Thinking-2507', 'Qwen3-30B-A3B-Thinking-2507'),
        ('Qwen/Qwen3-235B-A22B', 'Qwen3-235B-A22B-Thinking'),
        ('Qwen/Qwen3-235B-A22B-Thinking-2507', 'Qwen3-235B-A22B-Thinking-2507'),
        ('Qwen/Qwen3-0.6B-GPTQ-Int8', 'Qwen3-0.6B-Thinking-GPTQ-Int8'),
        ('Qwen/Qwen3-1.7B-GPTQ-Int8', 'Qwen3-1.7B-Thinking-GPTQ-Int8'),
        ('Qwen/Qwen3-4B-AWQ', 'Qwen3-4B-Thinking-AWQ'),
        ('Qwen/Qwen3-8B-AWQ', 'Qwen3-8B-Thinking-AWQ'),
        ('Qwen/Qwen3-14B-AWQ', 'Qwen3-14B-Thinking-AWQ'),
        ('Qwen/Qwen3-32B-AWQ', 'Qwen3-32B-Thinking-AWQ'),
        ('Qwen/Qwen3-30B-A3B-GPTQ-Int4', 'Qwen3-30B-A3B-Thinking-GPTQ-Int4'),
        ('Qwen/Qwen3-235B-A22B-GPTQ-Int4', 'Qwen3-235B-A22B-Thinking-GPTQ-Int4'),
        ('Qwen/Qwen3-VL-2B-Instruct', 'Qwen3-VL-2B-Instruct'),
        ('Qwen/Qwen3-VL-4B-Instruct', 'Qwen3-VL-4B-Instruct'),
        ('Qwen/Qwen3-VL-8B-Instruct', 'Qwen3-VL-8B-Instruct'),
        ('Qwen/Qwen3-VL-32B-Instruct', 'Qwen3-VL-32B-Instruct'),
        ('Qwen/Qwen3-VL-30B-A3B-Instruct', 'Qwen3-VL-30B-A3B-Instruct'),
        ('Qwen/Qwen3-VL-235B-A22B-Instruct', 'Qwen3-VL-235B-A22B-Instruct'),
        ('Qwen/Qwen3.5-0.8B-Base', 'Qwen3.5-0.8B-Base'),
        ('Qwen/Qwen3.5-2B-Base', 'Qwen3.5-2B-Base'),
        ('Qwen/Qwen3.5-4B-Base', 'Qwen3.5-4B-Base'),
        ('Qwen/Qwen3.5-9B-Base', 'Qwen3.5-9B-Base'),
        ('Qwen/Qwen3.5-35B-A3B-Base', 'Qwen3.5-35B-A3B-Base'),
        ('Qwen/Qwen3.5-0.8B', 'Qwen3.5-0.8B-Thinking'),
        ('Qwen/Qwen3.5-2B', 'Qwen3.5-2B-Thinking'),
        ('Qwen/Qwen3.5-4B', 'Qwen3.5-4B-Thinking'),
        ('Qwen/Qwen3.5-9B', 'Qwen3.5-9B-Thinking'),
        ('Qwen/Qwen3.5-27B', 'Qwen3.5-27B-Thinking'),
        ('Qwen/Qwen3.5-35B-A3B', 'Qwen3.5-35B-A3B-Thinking'),
        ('Qwen/Qwen3.5-122B-A10B', 'Qwen3.5-122B-A10B-Thinking'),
        ('Qwen/Qwen3.5-397B-A17B', 'Qwen3.5-397B-A17B-Thinking'),
    ],
    'DeepSeek 系列': [
        ('deepseek-ai/deepseek-llm-7b-base', 'DeepSeek-LLM-7B-Base'),
        ('deepseek-ai/deepseek-llm-67b-base', 'DeepSeek-LLM-67B-Base'),
        ('deepseek-ai/deepseek-llm-7b-chat', 'DeepSeek-LLM-7B-Chat'),
        ('deepseek-ai/deepseek-llm-67b-chat', 'DeepSeek-LLM-67B-Chat'),
        ('deepseek-ai/deepseek-math-7b-base', 'DeepSeek-Math-7B-Base'),
        ('deepseek-ai/deepseek-math-7b-instruct', 'DeepSeek-Math-7B-Instruct'),
        ('deepseek-ai/deepseek-moe-16b-base', 'DeepSeek-MoE-16B-Base'),
        ('deepseek-ai/deepseek-moe-16b-chat', 'DeepSeek-MoE-16B-Chat'),
        ('deepseek-ai/deepseek-coder-6.7b-base', 'DeepSeek-Coder-6.7B-Base'),
        ('deepseek-ai/deepseek-coder-7b-base-v1.5', 'DeepSeek-Coder-7B-Base'),
        ('deepseek-ai/deepseek-coder-33b-base', 'DeepSeek-Coder-33B-Base'),
        ('deepseek-ai/deepseek-coder-6.7b-instruct', 'DeepSeek-Coder-6.7B-Instruct'),
        ('deepseek-ai/deepseek-coder-7b-instruct-v1.5', 'DeepSeek-Coder-7B-Instruct'),
        ('deepseek-ai/deepseek-coder-33b-instruct', 'DeepSeek-Coder-33B-Instruct'),
        ('deepseek-ai/DeepSeek-V2-Lite', 'DeepSeek-V2-16B-Base'),
        ('deepseek-ai/DeepSeek-V2', 'DeepSeek-V2-236B-Base'),
        ('deepseek-ai/DeepSeek-V2-Lite-Chat', 'DeepSeek-V2-16B-Chat'),
        ('deepseek-ai/DeepSeek-V2-Chat', 'DeepSeek-V2-236B-Chat'),
        ('deepseek-ai/DeepSeek-V2-Chat-0628', 'DeepSeek-V2-0628-236B-Chat'),
        ('deepseek-ai/DeepSeek-V2.5', 'DeepSeek-V2.5-236B-Chat'),
        ('deepseek-ai/DeepSeek-V2.5-1210', 'DeepSeek-V2.5-1210-236B-Chat'),
        ('deepseek-ai/DeepSeek-Coder-V2-Lite-Base', 'DeepSeek-Coder-V2-16B-Base'),
        ('deepseek-ai/DeepSeek-Coder-V2-Base', 'DeepSeek-Coder-V2-236B-Base'),
        ('deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct', 'DeepSeek-Coder-V2-16B-Instruct'),
        ('deepseek-ai/DeepSeek-Coder-V2-Instruct', 'DeepSeek-Coder-V2-236B-Instruct'),
        ('deepseek-ai/DeepSeek-V3-Base', 'DeepSeek-V3-671B-Base'),
        ('deepseek-ai/DeepSeek-V3', 'DeepSeek-V3-671B-Chat'),
        ('deepseek-ai/DeepSeek-V3-0324', 'DeepSeek-V3-0324-671B-Chat'),
        ('deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B', 'DeepSeek-R1-1.5B-Distill'),
        ('deepseek-ai/DeepSeek-R1-Distill-Qwen-7B', 'DeepSeek-R1-7B-Distill'),
        ('deepseek-ai/DeepSeek-R1-Distill-Llama-8B', 'DeepSeek-R1-8B-Distill'),
        ('deepseek-ai/DeepSeek-R1-Distill-Qwen-14B', 'DeepSeek-R1-14B-Distill'),
        ('deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', 'DeepSeek-R1-32B-Distill'),
        ('deepseek-ai/DeepSeek-R1-Distill-Llama-70B', 'DeepSeek-R1-70B-Distill'),
        ('deepseek-ai/DeepSeek-R1-Zero', 'DeepSeek-R1-671B-Chat-Zero'),
        ('deepseek-ai/DeepSeek-R1', 'DeepSeek-R1-671B-Chat'),
        ('deepseek-ai/DeepSeek-R1-0528-Qwen3-8B', 'DeepSeek-R1-0528-8B-Distill'),
        ('deepseek-ai/DeepSeek-R1-0528', 'DeepSeek-R1-0528-671B-Chat'),
    ],
    'GLM / ChatGLM 系列': [
        ('ZhipuAI/chatglm3-6b-base', 'ChatGLM3-6B-Base'),
        ('ZhipuAI/chatglm3-6b', 'ChatGLM3-6B-Chat'),
        ('ZhipuAI/glm-4-9b', 'GLM-4-9B'),
        ('ZhipuAI/glm-4-9b-chat-hf', 'GLM-4-9B-Chat'),
        ('ZhipuAI/glm-4-9b-chat-1m', 'GLM-4-9B-1M-Chat'),
        ('ZhipuAI/GLM-4-9B-0414', 'GLM-4-0414-9B-Chat'),
        ('ZhipuAI/GLM-4-32B-Base-0414', 'GLM-4-0414-32B-Base'),
        ('ZhipuAI/GLM-4-32B-0414', 'GLM-4-0414-32B-Chat'),
        ('ZhipuAI/GLM-4.1V-9B-Base', 'GLM-4.1V-9B-Base'),
        ('ZhipuAI/GLM-4.1V-9B-Thinking', 'GLM-4.1V-9B-Thinking'),
        ('ZhipuAI/GLM-4.5-Air-Base', 'GLM-4.5-Air-Base'),
        ('ZhipuAI/GLM-4.5-Base', 'GLM-4.5-Base'),
        ('ZhipuAI/GLM-4.5-Air', 'GLM-4.5-Air-Thinking'),
        ('ZhipuAI/GLM-4.5', 'GLM-4.5-Thinking'),
        ('ZhipuAI/GLM-4.5V', 'GLM-4.5V-Air-Thinking'),
        ('ZhipuAI/GLM-4.6V', 'GLM-4.6V'),
        ('ZhipuAI/GLM-4.6V-Flash', 'GLM-4.6V-Flash'),
        ('ZhipuAI/GLM-4.7-Flash', 'GLM-4.7-Flash'),
        ('ZhipuAI/GLM-OCR', 'GLM-OCR'),
        ('ZhipuAI/GLM-Z1-9B-0414', 'GLM-Z1-0414-9B-Chat'),
        ('ZhipuAI/GLM-Z1-32B-0414', 'GLM-Z1-0414-32B-Chat'),
    ],
    'Llama 系列': [
        ('skyline2006/llama-7b', 'Llama-7B'),
        ('skyline2006/llama-13b', 'Llama-13B'),
        ('skyline2006/llama-30b', 'Llama-30B'),
        ('skyline2006/llama-65b', 'Llama-65B'),
        ('modelscope/Llama-2-7b-ms', 'Llama-2-7B'),
        ('modelscope/Llama-2-13b-ms', 'Llama-2-13B'),
        ('modelscope/Llama-2-70b-ms', 'Llama-2-70B'),
        ('modelscope/Llama-2-7b-chat-ms', 'Llama-2-7B-Chat'),
        ('modelscope/Llama-2-13b-chat-ms', 'Llama-2-13B-Chat'),
        ('modelscope/Llama-2-70b-chat-ms', 'Llama-2-70B-Chat'),
        ('LLM-Research/Meta-Llama-3-8B', 'Llama-3-8B'),
        ('LLM-Research/Meta-Llama-3-70B', 'Llama-3-70B'),
        ('LLM-Research/Meta-Llama-3-8B-Instruct', 'Llama-3-8B-Instruct'),
        ('LLM-Research/Meta-Llama-3-70B-Instruct', 'Llama-3-70B-Instruct'),
        ('LLM-Research/Llama3-8B-Chinese-Chat', 'Llama-3-8B-Chinese-Chat'),
        ('LLM-Research/Meta-Llama-3.1-8B', 'Llama-3.1-8B'),
        ('LLM-Research/Meta-Llama-3.1-70B', 'Llama-3.1-70B'),
        ('LLM-Research/Meta-Llama-3.1-405B', 'Llama-3.1-405B'),
        ('LLM-Research/Meta-Llama-3.1-8B-Instruct', 'Llama-3.1-8B-Instruct'),
        ('LLM-Research/Meta-Llama-3.1-70B-Instruct', 'Llama-3.1-70B-Instruct'),
        ('LLM-Research/Meta-Llama-3.1-405B-Instruct', 'Llama-3.1-405B-Instruct'),
        ('LLM-Research/Llama-3.2-1B', 'Llama-3.2-1B'),
        ('LLM-Research/Llama-3.2-3B', 'Llama-3.2-3B'),
        ('LLM-Research/Llama-3.2-1B-Instruct', 'Llama-3.2-1B-Instruct'),
        ('LLM-Research/Llama-3.2-3B-Instruct', 'Llama-3.2-3B-Instruct'),
        ('LLM-Research/Llama-3.3-70B-Instruct', 'Llama-3.3-70B-Instruct'),
        ('LLM-Research/Llama-4-Scout-17B-16E-Instruct', 'Llama-4-Scout-17B-16E-Instruct'),
        ('LLM-Research/Llama-4-Maverick-17B-128E-Instruct', 'Llama-4-Maverick-17B-128E-Instruct'),
    ],
    'Gemma 系列': [
        ('LLM-Research/gemma-2-2b', 'Gemma-2-2B'),
        ('LLM-Research/gemma-2-9b', 'Gemma-2-9B'),
        ('LLM-Research/gemma-2-27b', 'Gemma-2-27B'),
        ('LLM-Research/gemma-2-2b-it', 'Gemma-2-2B-Instruct'),
        ('LLM-Research/gemma-2-9b-it', 'Gemma-2-9B-Instruct'),
        ('LLM-Research/gemma-2-27b-it', 'Gemma-2-27B-Instruct'),
        ('LLM-Research/gemma-3-1b-pt', 'Gemma-3-1B'),
        ('LLM-Research/gemma-3-4b-pt', 'Gemma-3-4B'),
        ('LLM-Research/gemma-3-12b-pt', 'Gemma-3-12B'),
        ('LLM-Research/gemma-3-27b-pt', 'Gemma-3-27B'),
        ('LLM-Research/gemma-3-1b-it', 'Gemma-3-1B-Instruct'),
        ('LLM-Research/gemma-3-4b-it', 'Gemma-3-4B-Instruct'),
        ('LLM-Research/gemma-3-12b-it', 'Gemma-3-12B-Instruct'),
        ('LLM-Research/gemma-3-27b-it', 'Gemma-3-27B-Instruct'),
        ('LLM-Research/gemma-4-12b-it', 'Gemma-4-12B-Instruct'),
        ('LLM-Research/gemma-4-31b-it', 'Gemma-4-31B-Instruct'),
    ],
    'Mistral / Mixtral 系列': [
        ('LLM-Research/mistral-7b-v0.3', 'Mistral-7B-v0.3'),
        ('LLM-Research/Mistral-7B-Instruct-v0.3', 'Mistral-7B-Instruct-v0.3'),
        ('LLM-Research/Mistral-Nemo-Base-2407', 'Mistral-Nemo-Base-2407'),
        ('AI-ModelScope/Mistral-Nemo-Instruct-2407', 'Mistral-Nemo-Instruct-2407'),
        ('mistralai/Mistral-Small-24B-Instruct-2501', 'Mistral-Small-24B-Instruct-2501'),
        ('mistralai/Mistral-Small-3.1-24B-Instruct-2503', 'Mistral-Small-3.1-24B-Instruct'),
        ('mistralai/Mistral-Small-3.2-24B-Instruct-2506', 'Mistral-Small-3.2-24B-Instruct'),
        ('AI-ModelScope/Mixtral-8x7B-v0.1', 'Mixtral-8x7B-v0.1'),
        ('AI-ModelScope/Mixtral-8x7B-Instruct-v0.1', 'Mixtral-8x7B-v0.1-Instruct'),
    ],
    'InternLM 系列': [
        ('Shanghai_AI_Laboratory/internlm2_5-1_8b', 'InternLM2.5-1.8B'),
        ('Shanghai_AI_Laboratory/internlm2_5-7b', 'InternLM2.5-7B'),
        ('Shanghai_AI_Laboratory/internlm2_5-20b', 'InternLM2.5-20B'),
        ('Shanghai_AI_Laboratory/internlm2_5-1_8b-chat', 'InternLM2.5-1.8B-Chat'),
        ('Shanghai_AI_Laboratory/internlm2_5-7b-chat', 'InternLM2.5-7B-Chat'),
        ('Shanghai_AI_Laboratory/internlm2_5-20b-chat', 'InternLM2.5-20B-Chat'),
        ('Shanghai_AI_Laboratory/internlm3-8b-instruct', 'InternLM3-8B-Chat'),
    ],
    'InternVL 系列': [
        ('OpenGVLab/InternVL3-1B-hf', 'InternVL3-1B'),
        ('OpenGVLab/InternVL3-2B-hf', 'InternVL3-2B'),
        ('OpenGVLab/InternVL3-8B-hf', 'InternVL3-8B'),
        ('OpenGVLab/InternVL3-14B-hf', 'InternVL3-14B'),
        ('OpenGVLab/InternVL3-38B-hf', 'InternVL3-38B'),
        ('OpenGVLab/InternVL3-78B-hf', 'InternVL3-78B'),
    ],
    'Phi 系列': [
        ('LLM-Research/Phi-3.5-mini-instruct', 'Phi-3.5-4B-Instruct'),
        ('LLM-Research/Phi-3.5-MoE-instruct', 'Phi-3.5-MoE-42B-Instruct'),
        ('LLM-Research/phi-4', 'Phi-4-14B-Instruct'),
        ('LLM-Research/Phi-4-mini-instruct', 'Phi-4-3.8B-Instruct'),
    ],
    'MiniCPM 系列': [
        ('OpenBMB/MiniCPM4-0.5B', 'MiniCPM4-0.5B'),
        ('OpenBMB/MiniCPM4-8B', 'MiniCPM4-8B'),
        ('OpenBMB/MiniCPM4.1-8B', 'MiniCPM4.1-8B'),
        ('OpenBMB/MiniCPM-V-4', 'MiniCPM-V-4'),
        ('OpenBMB/MiniCPM-V-4_5', 'MiniCPM-V-4.5'),
        ('OpenBMB/MiniCPM-o-2_6', 'MiniCPM-o-2.6'),
    ],
    'Yi 系列': [
        ('01ai/Yi-1.5-6B', 'Yi-1.5-6B'),
        ('01ai/Yi-1.5-9B', 'Yi-1.5-9B'),
        ('01ai/Yi-1.5-34B', 'Yi-1.5-34B'),
        ('01ai/Yi-1.5-6B-Chat', 'Yi-1.5-6B-Chat'),
        ('01ai/Yi-1.5-9B-Chat', 'Yi-1.5-9B-Chat'),
        ('01ai/Yi-1.5-34B-Chat', 'Yi-1.5-34B-Chat'),
    ],
    'Hunyuan 系列': [
        ('Tencent-Hunyuan/Hunyuan-0.5B-Instruct', 'Hunyuan-0.5B-Instruct'),
        ('Tencent-Hunyuan/Hunyuan-1.8B-Instruct', 'Hunyuan-1.8B-Instruct'),
        ('Tencent-Hunyuan/Hunyuan-4B-Instruct', 'Hunyuan-4B-Instruct'),
        ('Tencent-Hunyuan/Hunyuan-7B-Instruct', 'Hunyuan-7B-Instruct'),
        ('Tencent-Hunyuan/Hunyuan-A13B-Instruct', 'Hunyuan-A13B-Instruct'),
    ],
    'MiMo 系列': [
        ('XiaomiMiMo/MiMo-7B-Base', 'MiMo-7B-Base'),
        ('XiaomiMiMo/MiMo-7B-SFT', 'MiMo-7B-Instruct'),
        ('XiaomiMiMo/MiMo-7B-RL', 'MiMo-7B-RL'),
        ('XiaomiMiMo/MiMo-VL-7B-RL', 'MiMo-VL-7B-RL'),
    ],
    'Kimi 系列': [
        ('moonshotai/Kimi-Dev-72B', 'Kimi-Dev-72B'),
        ('moonshotai/Kimi-VL-A3B-Instruct', 'Kimi-VL-A3B-Instruct'),
        ('moonshotai/Kimi-VL-A3B-Thinking', 'Kimi-VL-A3B-Thinking'),
        ('moonshotai/Moonlight-16B-A3B-Instruct', 'Moonlight-16B-A3B-Instruct'),
    ],
    '其他模型': [
        ('HuggingFaceTB/SmolLM2-135M-Instruct', 'SmolLM2-135M-Instruct'),
        ('HuggingFaceTB/SmolLM2-360M-Instruct', 'SmolLM2-360M-Instruct'),
        ('HuggingFaceTB/SmolLM2-1.7B-Instruct', 'SmolLM2-1.7B-Instruct'),
        ('infly/OpenCoder-1.5B-Instruct', 'OpenCoder-1.5B-Instruct'),
        ('infly/OpenCoder-8B-Instruct', 'OpenCoder-8B-Instruct'),
        ('ByteDance-Seed/Seed-Coder-8B-Instruct', 'Seed-Coder-8B-Instruct'),
        ('LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct', 'EXAONE-3.0-7.8B-Instruct'),
        ('PaddlePaddle/ERNIE-4.5-0.3B-PT', 'ERNIE-4.5-0.3B'),
        ('PaddlePaddle/ERNIE-4.5-21B-A3B-PT', 'ERNIE-4.5-21B-A3B'),
        ('rednote-hilab/dots.ocr', 'dots.ocr'),
    ],
}
